version: '3.9'
services:
  #PHP Service
  app:
    build:
      context: ./.docker/php/8.3
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - nginx
      - db
      - redis
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    tty: true
    ports:
      - "8000:80"
    environment:
      TZ: America/Cuiaba
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/logs/nginx:/var/log/nginx
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
      TZ: America/Cuiaba
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - UPLOAD_LIMIT=500M
      - MEMORY_LIMIT=1024M
      - POST_MAX_SIZE=500M
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge